SELECT *FROM NHANVIEN
DECLARE @MAX INT , @NUM INT
SELECT @MAX = MAX (CAST(MANV AS INT))
FROM NHANVIEN
SET @NUM = 1
WHILE @NUM <= @MAX
BEGIN
	IF @NUM %2 = 0
	SELECT HONV , TENLOT , TENNV
	FROM NHANVIEN
	WHERE CAST(MANV AS INT) = @NUM
	SET @NUM = @NUM + 1
END
GO 
SELECT *FROM NHANVIEN
DECLARE @MAX INT , @NUM INT
SELECT @MAX = MAX (CAST(MANV AS INT))
FROM NHANVIEN
SET @NUM = 1
WHILE @NUM <= @MAX
BEGIN
    IF @NUM = 4
	BEGIN
	    SET @NUM = @NUM + 1
		CONTINUE
	END
	IF @NUM %2 = 0
	SELECT HONV , TENLOT , TENNV
	FROM NHANVIEN
	WHERE CAST(MANV AS INT) = @NUM
	SET @NUM = @NUM + 1
END

