/*CâuIII.1*/
SELECT MASP , TENSP
FROM SANPHAM
WHERE NUOCSX = 'TRUNG QUỐC'
/*CâuIII.2*/
SELECT MASP , TENSP
FROM SANPHAM
WHERE DVT = 'cây' OR DVT = 'quyển'
/*CâuIII.3*/
SELECT MASP , TENSP
FROM SANPHAM
WHERE MASP LIKE 'B%01'
/*CâuIII.4*/
SELECT MASP , TENSP
FROM SANPHAM
WHERE NUOCSX = 'TRUNG QUỐC' AND GIA BETWEEN 30000 AND 40000
/*CâuIII.5*/
SELECT MASP , TENSP
FROM SANPHAM
WHERE (NUOCSX = 'TRUNG QUỐC' OR NUOCSX = 'THÁI LAN') AND GIA BETWEEN 30000 AND 40000
/*CâuIII.6*/
SELECT SOHD , TRIGIA
FROM HOADON
WHERE NGHD = '1/1/2007' AND NGHD = '2/1/2007'
/*CâuIII.7*/
SELECT SOHD , TRIGIA
FROM HOADON
WHERE MONTH(NGHD) = 1 AND YEAR(NGHD) = 2007
ORDER BY NGHD ASC , TRIGIA DESC
/*CâuIII.8*/
SELECT A.MAKH,HOTEN
FROM  HOADON A, KHACHHANG B
WHERE A.MAKH=B.MAKH AND NGHD='1/1/2007'
/*CâuIII.9*/
SELECT SOHD,TRIGIA
FROM  HOADON A, NHANVIEN B
WHERE A.MANV=B.MANV AND NGHD='28/10/2006' AND HOTEN='NGUYEN VAN B' 
/*CâuIII.10*/
SELECT C.MASP, TENSP
FROM  HOADON A, KHACHHANG B, CTHD C, SANPHAM D
WHERE A.MAKH=B.MAKH AND A.SOHD=C.SOHD AND C.MASP=D.MASP AND MONTH(NGHD)=10 AND YEAR(NGHD)=2006 AND HOTEN='NGUYEN VAN A' 

