//Câu 8
ALTER TABLE SANPHAM 
ADD CONSTRAINT CHECK_GIA CHECK(GIA>=500)
//Câu 9
ALTER TABLE CTHD 
ADD CONSTRAINT CHECK_SL CHECK(SL>=1)
//Câu 10
ALTER TABLE KHACHHANG ADD CONSTRAINT CHECK_NGDK CHECK (NGDK>NGSINH)
//Câu 11
CREATE TRIGGER UPDATE_KH_TV
ON KHACHHANG
FOR UPDATE
AS
 DECLARE @NGDK SMALLDATETIME, 
   @NGHD SMALLDATETIME

 SELECT @NGDK=NGDK
 FROM  INSERTED
 
 IF(@NGDK>ANY(SELECT NGHD
    FROM  HOADON A, INSERTED I
    WHERE A.MAKH=I.MAKH))
  BEGIN
   ROLLBACK TRAN
   PRINT 'Sai rồi!'
  END
 ELSE
  PRINT 'Thành công'
//Câu 12
CREATE TRIGGER KIEMTRA_NGAYVL
ON NHANVIEN
FOR UPDATE
AS
 DECLARE @NGVL SMALLDATETIME, 
   @NGHD SMALLDATETIME

 SELECT @NGVL=NGVL
 FROM  INSERTED
 
 IF(@NGVL>ANY(SELECT NGHD
    FROM  HOADON A, INSERTED I
    WHERE A.MANV=I.MANV))
  BEGIN
   ROLLBACK TRAN
   PRINT 'Sai rồi!'
  END
 ELSE
  PRINT' Thành công!'
//Câu 13
CREATE TRIGGER KIEMTRA_HOADON
ON CTHD
FOR DELETE,UPDATE
AS
 DECLARE @SL  INT,
   @SOHD INT

 SELECT @SL=COUNT(A.SOHD),@SOHD=D.SOHD
 FROM  DELETED D,CTHD A
 WHERE A.SOHD=D.SOHD
 GROUP BY  D.SOHD

 IF(@SL<1)
  BEGIN
   DELETE FROM HOADON
   WHERE  SOHD=@SOHD
   PRINT 'DA DELETE CTHD CUOI CUNG CUA HOADON TREN'
  END
//Câu 14
CREATE TRIGGER THEM_HOADON
ON HOADON
FOR INSERT
AS
 UPDATE HOADON
 SET  TRIGIA=0
 WHERE SOHD=(SELECT  SOHD
    FROM  INSERTED)
 PRINT'Đã thêm giá trị ban đầu = 0'
//Câu 15
CREATE TRIGGER THEM_KHACHHANG
ON KHACHHANG
FOR INSERT
AS
 DECLARE @MAKH CHAR(4)

 SELECT @MAKH=MAKH
 FROM  INSERTED
 
 UPDATE KHACHHANG
 SET  DOANHSO=0
 WHERE MAKH=@MAKH

 PRINT 'Đã thêm khách trị giá = 0'