CREATE TABLE LOP(
MALOP CHAR(10) PRIMARY KEY,
TENLOP VARCHAR(20),
SISO INT
);
CREATE TABLE SINHVIEN(
MASV CHAR(10) PRIMARY KEY,
HOTEN NVARCHAR(30),
NGAYSINH SMALLDATETIME,
MALOP CHAR(10) CONSTRAINT FK_MALOP REFERENCES LOP(MALOP)
);
CREATE TABLE MONHOC(
MAMH CHAR(10) PRIMARY KEY,
TENMH NVARCHAR(30)
);
CREATE TABLE KETQUA(
MASV CHAR(10) PRIMARY KEY,
MAMH CHAR(10) ,
DIEMTHI FLOAT,
CONSTRAINT FK_MASV FOREIGN KEY(MASV) REFERENCES SINHVIEN(MASV),
CONSTRAINT FK_MAMH FOREIGN KEY(MASV) REFERENCES SINHVIEN(MAMH),
CONSTRAINT FK_MASV_MAMH PRIMARY KEY(MASV , MAMH),
);
INSERT LOP VALUES
('A101' , 'CNTT1' , '30'),
('A102' , 'CNTT2' , '34'),
('A103' , 'CNTT3' , '30')
INSERT SINHVIEN VALUES
('008' , 'NGUYỄN HOÀI ANH' , '10-10-2000' , 'A101'),
('009' , 'NGUYỄN VĂN AN' , '8-12-2002' , 'A101'),
('005' , 'TRẦN NGUYỄN BÁ KHANG' , '5-20-2002' ,'A101')
INSERT MONHOC VALUES
('01' , 'HQTCSDL'),
('02' , 'CSDLNC'),
('03' , 'VTCB')
INSERT KETQUA VALUES
('008' , '01' , 8.0),
('008' , '02' , 7.5),
('009' , '03' , 7.2),
('005' , '03' , 8.2)
-----CÂU 1-----
CREATE FUNCTION DIEMTB (@MASV CHAR(10))
RETURNS FLOAT
AS
  BEGIN
      DECLARE @TB FLOAT
	  SET @TB = (SELECT AVG(DIEMTHI)
	  FROM KETQUA
	  WHERE MASV = @MASV)
	  RETURN @TB
  END
GO
SELECT dbo.DIEMTB('01')
-----CÂU 2-----
CREATE FUNCTION TBLOP(@MALOP CHAR(10)
RETURNS TABLE
AS
  RETURN
       SELECT S.MASV , HOTEN , TRUNGBINH = dbo.DIEMTB(S.MASV)
	   FROM Sinhvien S JOIN KETQUA k ON S.MASV=k.MASV
	   WHERE MALOP=@MALOP
	   GROUP BY S.MASV, HOTEN-----CÂU 3-----CREATE PROC KTRA @MASV CHAR(5)
AS
BEGIN
 DECLARE @n INT
 SET @n=(SELECT COUNT(*) FROM KETQUA WHERE MASV=@MASV)
 IF @n=0
 PRINT 'sinh vien '+@MASV + 'khong thi mon nao'
 ELSE
 PRINT 'sinh vien '+ @MASV+ 'thi '+cast(@n as char(2))+ 'mon'
END
GO
EXEC KTRA '01'-----CÂU 4-----CREATE TRIGGER updatesslop
ON SINHVIEN
FOR INSERT
AS
BEGIN
 DECLARE @ss int
 SET @ss=(select count(*) from sinhvien s
 WHERE malop in(select malop from inserted))
 IF @ss>10
 BEGIN
 PRINT 'Lop day'
 ROLLBACK TRAN
 END
 ELSE
 BEGIN
 UPDATE LOP
 SET SiSo=@ss
 WHERE malop in (select malop from inserted)
 END