CREATE PROCEDURE sp_HELLO
       @TEN VARCHAR(20)
AS
BEGIN
    PRINT 'XIN CHÀO' + @TEN;
END
ALTER PROCEDURE sp_HELLO
      @TEN VARCHAR(20)
AS
BEGIN
    PRINT 'XIN CHÀO' + @TEN;
END
EXECUTE sp_HELLO N' HÙNG';