CREATE PROCEDURE sp_ThemPhong
@TENPHG NVARCHAR(15) , @MAPHG INT,
@TRPHG NVARCHAR(9) , @NG_NHANCHUC DATE
AS 
IF EXISTS(SELECT * FROM PHONGBAN WHERE MAPHG = @MAPHG)
UPDATE PHONGBAN SET TENPHG = @TENPHG , TRPHG = @TRPHG , NG_NHANCHUC = @NG_NHANCHUC
WHERE MAPHG = @MAPHG
ELSE
INSERT INTO PHONGBAN
VALUES (@TENPHG , @MAPHG , @TRPHG , @NG_NHANCHUC)
DROP PROC sp_ThemPhong
GO
EXEC sp_ThemPhong 'CNTT', 6,'008','1985-01-01'