SELECT *FROM PHONGBAN
BEGIN TRY
	INSERT INTO PHONGBAN(TENPHG,MAPHG,TRPHG, NG_NHANCHUC)
	VALUES (N'Sản Xuất',5, '009','2022/11/24');
	PRINT N'Thêm dữ liệu thành công!'
END TRY

BEGIN CATCH
	PRINT N'failure : Chèn dữ  liệu không thành công!'
END CATCH
GO
BEGIN TRY
      DECLARE @CHIA INT;
	  SET @CHIA = 10/0;
END TRY
BEGIN CATCH
      DECLARE @ERRORMESSAGE NVARCHAR(2048) , @ErSeverity INT , @ERRORSTATE INT;
	  SELECT @ERRORMESSAGE = ERROR_MESSAGE(),
	         @ErSeverity = ERROR_SEVERITY(),
			 @ERRORSTATE = ERROR_STATE()
	  RAISERROR (@ERRORMESSAGE , @ERRORSEVERITY , @ERRORSTATE)
END CATCH

