CREATE TRIGGER trg_KiemTraLuong
       ON NHANVIEN
	   FOR INSERT , UPDATE
AS
       IF(SELECT LUONG FROM INSERTED) < 15000
	   BEGIN
	       PRINT N'LUONG < 15000'
		   ROLLBACK TRANSACTION
	   END
SELECT * FROM NHANVIEN
INSERT INTO [dbo].[NHANVIEN] ([HONV] , [TENLOT] , [TENNV] , [MANV] , [NGSINH] , [DCHI] , [PHAI] , [LUONG] , [MA_NQL] , [PHG])
VALUES(N'NGUYỄN' , N'TRẦN' , N'KHANH' , '013' , '8-12-2000' , 'Lac Long Quân-HCM' , 'NAM' , '2000' , '098' , '2')
GO
CREATE TRIGGER trg_KiemTraDoTuoi
       ON NHANVIEN
	   FOR INSERT
AS
       DECLARE @AGE INT
	   SELECT @AGE = DATEDIFF(YEAR , NGSINH , GETDATE()) + 1 FROM INSERTED
	   IF @AGE < 18 OR @AGE > 65
	   BEGIN 
	       PRINT N'Tuổi không hợp lệ'
		   ROLLBACK TRANSACTION
	   END

INSERT INTO [dbo].[NHANVIEN] ([HONV] , [TENLOT] , [TENNV] , [MANV] , [NGSINH] , [DCHI] , [PHAI] , [LUONG] , [MA_NQL] , [PHG])
VALUES(N'TRẦN' , N'BẢO' , N'ĐẠI' , '014' , '10-11-1999' , 'Âu Cơ-HCM' , 'NAM' , 16000 , '004' , 1)
GO
CREATE TRIGGER trg_KiemTraDiaChi
       ON NHANVIEN
	   FOR UPDATE
AS
       IF EXISTS (SELECT DCHI FROM INSERTED WHERE DCHI LIKE '%HCM%')
	   BEGIN
	       PRINT N'Không thể cập nhật nhân viên ở TPHCM'
		   ROLLBACK TRANSACTION
	   END
UPDATE [dbo].[NHANVIEN]
SET [PHAI] = 'NAM'
WHERE MANV = '001'