CREATE TRIGGER trg_SumEmpsForUpdate
       ON NHANVIEN
	   AFTER UPDATE
AS
       DECLARE @MALE INT , @FEMALE INT
	   IF (SELECT TOP 1 PHAI FROM DELETED) != (SELECT TOP 1 PHAI FROM INSERTED)
	   BEGIN
	   SELECT COUNT(MANV) FROM NHANVIEN WHERE PHAI = N'NAM'
	   SELECT COUNT(MANV) FROM NHANVIEN WHERE PHAI = N'NỮ'
	   PRINT N'Tổng số nhân viên nữ là: ' + CAST(@FEMALE AS VARCHAR)
	   PRINT N'Tổng số nhân viên nam là: ' + CAST(@MALE AS VARCHAR)
	   END

UPDATE [dbo].[NHANVIEN]
   SET [HONV] = 'HOA'
      ,[PHAI] = N'Nữ'
 WHERE  MaNV = '114'
