CREATE TRIGGER trg_SumEmps
       ON NHANVIEN
	   AFTER INSERT
AS
       DECLARE @MALE INT , @FEMALE INT
	   SELECT COUNT(MANV) FROM NHANVIEN WHERE PHAI = N'NAM'
	   SELECT COUNT(MANV) FROM NHANVIEN WHERE PHAI = N'NỮ'
	   PRINT N'Tổng số nhân viên nam là: ' + CAST(@MALE AS VARCHAR)
	   PRINT N'Tổng số nhân viên nữ là: ' + CAST(@FEMALE AS VARCHAR)

INSERT INTO [dbo].[NHANVIEN] ([HONV] , [TENLOT] , [TENNV] , [MANV] , [NGSINH] , [DCHI] , [PHAI] , [LUONG] , [MA_NQL] , [PHG])
VALUES(N'NGUYỄN' , N'GIA' , N'KHIÊM' , '006' , '10-8-1998' , 'Hoà Bình-HCM' , 'NAM' , 30000 , '009' , 1)

SELECT * FROM NHANVIEN