/*Câu1a*/
IF OBJECT_ID('FN_TUOI_NV') IS NOT NULL
DROP FUNCTION FN_TUOI_NV
GO
CREATE FUNCTION FN_TUOI_NV( @MANHANVIEN NVARCHAR(9))
RETURNS INT
AS
BEGIN
RETURN(SELECT YEAR(GETDATE())-YEAR (NGSINH)
FROM NHANVIEN WHERE MANV=@MANHANVIEN)
END
PRINT N'Tuổi của nhân viên là: ' + CAST (DBO.FN_TUOI_NV('001') AS VARCHAR(5))
SELECT * FROM NHANVIEN 
/*Câu1b*/
SELECT COUNT (MADA)	FROM PHANCONG WHERE MA_NVIEN='001'
SELECT * FROM PHANCONG
IF OBJECT_ID('FN_DEAN_NV') IS NOT NULL
DROP FUNCTION FN_DEAN_NV
GO
CREATE FUNCTION FN_DEAN_NV( @MANHANVIEN NVARCHAR(9))
RETURNS INT
AS
BEGIN
RETURN(SELECT COUNT (MADA)	FROM PHANCONG WHERE MA_NVIEN=@MANHANVIEN)
END
PRINT N'Số lượng đề án của nhân viên:' + CAST (DBO.FN_DEAN_NV('001') AS VARCHAR(5))
SELECT * FROM NHANVIEN
/*Câu1c*/
IF OBJECT_ID('FN_PHAI_NV') IS NOT NULL
DROP FUNCTION FN_PHAI_NV
GO
CREATE FUNCTION FN_PHAI_NV( @GT NVARCHAR(4))
RETURNS INT
AS
BEGIN
RETURN(SELECT COUNT (*)	FROM NHANVIEN WHERE UPPER(PHAI)=UPPER(@GT))
END
SELECT * FROM NHANVIEN
PRINT N'Số lượng nhân viên nam: ' + CAST (DBO.FN_PHAI_NV('NAM') AS VARCHAR(5))
PRINT N'Số lượng nhân viên nữ: ' + CAST (DBO.FN_PHAI_NV(N'NỮ') AS VARCHAR(5))
/*Câu1d*/
IF OBJECT_ID('FN_LUONG_NV_PB') IS NOT NULL
DROP FUNCTION FN_LUONG_NV_PB
GO
CREATE FUNCTION FN_LUONG_NV_PB(@TENPHONGBAN NVARCHAR(15))
RETURNS @LISTNV TABLE(HOTEN NVARCHAR(60), LUONG FLOAT)
AS 
BEGIN
DECLARE @LUONGTB FLOAT 
SELECT @LUONGTB=AVG(LUONG) FROM NHANVIEN
INNER JOIN PHONGBAN ON PHONGBAN.MAPHG=NHANVIEN.PHG
WHERE UPPER(TENPHG)=UPPER(@TENPHONGBAN)
INSERT INTO @LISTNV
SELECT CONCAT(HONV, ' ', TENLOT,' ',TENNV), LUONG FROM NHANVIEN 
WHERE LUONG>@LUONGTB
RETURN
END
SELECT * FROM PHONGBAN
SELECT * FROM DBO.FN_LUONG_NV_PB(N'ĐIỀU HÀNH')
/*Câu1e*/
IF OBJECT_ID('FN_PB_NV_DEAN') IS NOT NULL
DROP FUNCTION FN_PB_NV_DEAN
GO
CREATE FUNCTION FN_PB_NV_DEAN (@MAPB INT)
RETURNS @LISTPB TABLE (TENPHONG NVARCHAR(20), HOTENNV NVARCHAR(60),SLDUAN INT)
AS 
BEGIN
INSERT INTO @LISTPB
SELECT PHONGBAN.TENPHG, CONCAT(HONV,' ', TENLOT, ' ', TENNV), COUNT(MADA) 
FROM PHONGBAN INNER JOIN DEAN ON DEAN.PHONG=PHONGBAN.MAPHG 
INNER JOIN NHANVIEN ON NHANVIEN.PHG=PHONGBAN.MAPHG 
WHERE PHONGBAN.MAPHG=@MAPB
GROUP BY TENPHG, HONV, TENLOT, TENNV
RETURN
END
SELECT * FROM DBO.FN_PB_NV_DEAN('005');
